import { Song } from '../../../shared/scoring';

// The daily rotation lives server-side ONLY, so the answer (and the future
// schedule) never ships to the browser. GET /api/daily reveals just the
// current title/artist; the BPM comes back only with a scored run.
// BPMs verified against Tunebat/SongBPM/GetSongBPM et al. (2026-07-22). Songs
// with a genuine half/double-time feel (Hey Ya!, Wonderwall, Umbrella,
// Hotel California, Footloose…) store the felt clap-along tempo — the
// octave-aware scoring below accepts either feel, so the choice only affects
// the "actual BPM" shown on reveal. Never reorder or remove entries: a song's
// index decides which day it appears, so edits in place or appends only.

export const SONGS: Song[] = [
  { title: 'Toxic', artist: 'Britney Spears', bpm: 143 },
  { title: 'Billie Jean', artist: 'Michael Jackson', bpm: 117 },
  { title: 'Dancing Queen', artist: 'ABBA', bpm: 101 },
  { title: "Stayin' Alive", artist: 'Bee Gees', bpm: 104 },
  { title: 'Uptown Funk', artist: 'Mark Ronson ft. Bruno Mars', bpm: 115 },
  { title: 'Shape of You', artist: 'Ed Sheeran', bpm: 96 },
  { title: 'Rolling in the Deep', artist: 'Adele', bpm: 105 },
  { title: 'Hey Ya!', artist: 'OutKast', bpm: 158 },
  { title: 'Beat It', artist: 'Michael Jackson', bpm: 139 },
  { title: 'Smells Like Teen Spirit', artist: 'Nirvana', bpm: 117 },
  { title: 'Take On Me', artist: 'a-ha', bpm: 169 },
  { title: 'Wonderwall', artist: 'Oasis', bpm: 87 },
  { title: 'I Want It That Way', artist: 'Backstreet Boys', bpm: 99 },
  { title: 'Poker Face', artist: 'Lady Gaga', bpm: 119 },
  { title: 'Bad Guy', artist: 'Billie Eilish', bpm: 135 },
  { title: 'Blinding Lights', artist: 'The Weeknd', bpm: 171 },
  { title: 'Happy', artist: 'Pharrell Williams', bpm: 160 },
  { title: 'Shake It Off', artist: 'Taylor Swift', bpm: 160 },
  { title: "Can't Stop the Feeling!", artist: 'Justin Timberlake', bpm: 113 },
  { title: 'Seven Nation Army', artist: 'The White Stripes', bpm: 124 },
  { title: 'Superstition', artist: 'Stevie Wonder', bpm: 100 },
  { title: 'I Will Survive', artist: 'Gloria Gaynor', bpm: 117 },
  { title: 'Like a Prayer', artist: 'Madonna', bpm: 111 },
  { title: "Livin' on a Prayer", artist: 'Bon Jovi', bpm: 123 },
  { title: "Don't Stop Believin'", artist: 'Journey', bpm: 119 },
  { title: "Hips Don't Lie", artist: 'Shakira', bpm: 100 },
  { title: 'Get Lucky', artist: 'Daft Punk', bpm: 116 },
  { title: 'Firework', artist: 'Katy Perry', bpm: 124 },
  { title: 'Viva la Vida', artist: 'Coldplay', bpm: 138 },
  { title: 'Crazy in Love', artist: 'Beyoncé', bpm: 99 },
  { title: 'We Will Rock You', artist: 'Queen', bpm: 81 },
  { title: 'Africa', artist: 'Toto', bpm: 92 },
  { title: 'Mr. Brightside', artist: 'The Killers', bpm: 148 },
  { title: 'Gangnam Style', artist: 'PSY', bpm: 132 },
  { title: 'Sweet Caroline', artist: 'Neil Diamond', bpm: 127 },
  { title: '...Baby One More Time', artist: 'Britney Spears', bpm: 93 },
  { title: 'My Girl', artist: 'The Temptations', bpm: 105 },
  { title: "U Can't Touch This", artist: 'MC Hammer', bpm: 133 },
  { title: 'Respect', artist: 'Aretha Franklin', bpm: 115 },
  { title: 'Ice Ice Baby', artist: 'Vanilla Ice', bpm: 116 },
  { title: 'Twist and Shout', artist: 'The Beatles', bpm: 124 },
  { title: 'What Is Love', artist: 'Haddaway', bpm: 124 },
  { title: 'Brown Eyed Girl', artist: 'Van Morrison', bpm: 150 },
  { title: 'Macarena', artist: 'Los del Río', bpm: 103 },
  { title: 'I Heard It Through the Grapevine', artist: 'Marvin Gaye', bpm: 117 },
  { title: 'Wannabe', artist: 'Spice Girls', bpm: 110 },
  { title: "(I Can't Get No) Satisfaction", artist: 'The Rolling Stones', bpm: 136 },
  { title: 'Barbie Girl', artist: 'Aqua', bpm: 130 },
  { title: 'Hey Jude', artist: 'The Beatles', bpm: 74 },
  { title: 'Believe', artist: 'Cher', bpm: 133 },
  { title: 'Jolene', artist: 'Dolly Parton', bpm: 111 },
  { title: 'Blue (Da Ba Dee)', artist: 'Eiffel 65', bpm: 128 },
  { title: 'Mamma Mia', artist: 'ABBA', bpm: 137 },
  { title: 'No Scrubs', artist: 'TLC', bpm: 93 },
  { title: 'Night Fever', artist: 'Bee Gees', bpm: 109 },
  { title: "It's My Life", artist: 'Bon Jovi', bpm: 120 },
  { title: 'Y.M.C.A.', artist: 'Village People', bpm: 127 },
  { title: 'Lose Yourself', artist: 'Eminem', bpm: 86 },
  { title: 'September', artist: 'Earth, Wind & Fire', bpm: 126 },
  { title: 'In da Club', artist: '50 Cent', bpm: 90 },
  { title: 'Hotel California', artist: 'Eagles', bpm: 74 },
  { title: 'Yeah!', artist: 'Usher ft. Lil Jon & Ludacris', bpm: 105 },
  { title: 'Sweet Home Alabama', artist: 'Lynyrd Skynyrd', bpm: 98 },
  { title: 'Since U Been Gone', artist: 'Kelly Clarkson', bpm: 131 },
  { title: 'Crocodile Rock', artist: 'Elton John', bpm: 150 },
  { title: 'SexyBack', artist: 'Justin Timberlake', bpm: 117 },
  { title: 'Thriller', artist: 'Michael Jackson', bpm: 118 },
  { title: 'Umbrella', artist: 'Rihanna ft. Jay-Z', bpm: 87 },
  { title: 'Girls Just Want to Have Fun', artist: 'Cyndi Lauper', bpm: 120 },
  { title: 'Single Ladies (Put a Ring on It)', artist: 'Beyoncé', bpm: 97 },
  { title: 'Like a Virgin', artist: 'Madonna', bpm: 120 },
  { title: 'I Gotta Feeling', artist: 'The Black Eyed Peas', bpm: 128 },
  { title: 'Sweet Dreams (Are Made of This)', artist: 'Eurythmics', bpm: 126 },
  { title: 'Party in the U.S.A.', artist: 'Miley Cyrus', bpm: 96 },
  { title: 'Every Breath You Take', artist: 'The Police', bpm: 117 },
  { title: 'Call Me Maybe', artist: 'Carly Rae Jepsen', bpm: 120 },
  { title: 'Eye of the Tiger', artist: 'Survivor', bpm: 109 },
  { title: 'Counting Stars', artist: 'OneRepublic', bpm: 122 },
  { title: 'I Wanna Dance with Somebody', artist: 'Whitney Houston', bpm: 119 },
  { title: 'All About That Bass', artist: 'Meghan Trainor', bpm: 134 },
  { title: 'Footloose', artist: 'Kenny Loggins', bpm: 174 },
  { title: 'Despacito', artist: 'Luis Fonsi ft. Daddy Yankee', bpm: 89 },
  { title: 'Wake Me Up Before You Go-Go', artist: 'Wham!', bpm: 81 },
  { title: 'Havana', artist: 'Camila Cabello', bpm: 105 },
  { title: 'Never Gonna Give You Up', artist: 'Rick Astley', bpm: 113 },
  { title: 'Watermelon Sugar', artist: 'Harry Styles', bpm: 95 },
  { title: 'Walking on Sunshine', artist: 'Katrina & The Waves', bpm: 110 },
  { title: "Don't Start Now", artist: 'Dua Lipa', bpm: 124 },
  { title: 'Another One Bites the Dust', artist: 'Queen', bpm: 110 },
  { title: 'Levitating', artist: 'Dua Lipa', bpm: 103 },
  { title: "Don't Stop Me Now", artist: 'Queen', bpm: 156 },
  { title: 'Espresso', artist: 'Sabrina Carpenter', bpm: 104 },
];

export function songForDay(day: number): Song {
  const i = (((day - 1) % SONGS.length) + SONGS.length) % SONGS.length;
  return SONGS[i];
}
